name: Code quality

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        env:
          PORT: ${{ secrets.PORT }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run lint:check
      - run: npm run format:check
      - run: npm run test:coverage
