name: code quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    name: code quality
    runs-on: ubuntu-latest

    env:
      DB_PORT: 5432
      DB_HOST: localhost
      DB_NAME: content-management-api-test
      DB_USER: test
      DB_PASSWORD: test

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: install dependencies
        run: npm ci

      - name: print environment variables
        run: |
          echo "DB_PORT: $DB_PORT"
          echo "DB_HOST: $DB_HOST"
          echo "DB_NAME: $DB_NAME"
          echo "DB_USER: $DB_USER"
          echo "DB_PASSWORD: $DB_PASSWORD"

      - name: lint check
        run: npm run lint:check

      - name: format check
        run: npm run format:check

      - name: test coverage
        run: npm run test:coverage
